# TODO: remove this
inherit_from: .rubocop_todo.yml

inherit_gem:
  theforeman-rubocop:
    - default.yml

AllCops:
  TargetRubyVersion: 2.7

MethodLength:
  Description: "Avoid methods longer than 30 lines of code."
  Max: 30 # default is 10

StringLiterals:
  Enabled: false

HashSyntax:
  Enabled: false

SpaceInsideHashLiteralBraces:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 140

FormatString:
  Enabled: false # we use % for i18n

RedundantSelf:
  Enabled: false

RedundantReturn:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/SymbolProc:
  Enabled: false
